import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import MainNavigation from "@/components/main-navigation";
import Footer from "@/components/footer";

const gotham = localFont({
  src: "./fonts/gotham-book.woff",
  variable: "--font-gotham",
  weight: "100 900",
});

const gothamBold = localFont({
  src: "./fonts/gotham-bold.woff",
  variable: "--font-gotham-bold",
  weight: "700",
});

const gothamMedium = localFont({
  src: "./fonts/gotham-medium.woff",
  variable: "--font-gotham-medium",
  weight: "500",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${gotham.variable} ${gothamBold.variable} ${gothamMedium.variable} antialiased relative`}
      >
        <MainNavigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
